export const navigationItems = [
  { title: 'Installation', href: '/docs/getting-started/installation' },
  { title: 'Usage', href: '/docs/getting-started/usage' },
  { title: 'Components', href: '/docs/components' },
  { title: 'Location Picker', href: '/docs/components/location-picker' },
  { title: 'Currency Manager', href: '/docs/components/currency-manager' },
  { title: 'Infinite Scroll', href: '/docs/components/infinite-scroll' },
  { title: 'File Explorer', href: '/docs/components/file-explorer' },
  { title: 'Multi-Step Form Wrapper', href: '/docs/components/multi-step-form-wrapper' },
  { title: 'Password Strength Meter', href: '/docs/components/strength-meter' },
  { title: 'File Uploader', href: '/docs/components/file-uploader' },
  { title: 'useToggle', href: '/docs/hooks/use-toggle' },
  { title: 'useLocalStorage', href: '/docs/hooks/use-local-storage' },
  { title: 'Colors', href: '/docs/utilities/colors' },
  { title: 'Typography', href: '/docs/utilities/typography' },
];
